services:
  backend:
    build: ./backend
    container_name: task-queue-backend
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
    restart: unless-stopped
    tty: false

  frontend:
    build: ./frontend
    container_name: task-queue-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    restart: unless-stopped
    tty: false
